version: '3.7'
services:
  dev:
    build: .
    volumes:
      - .:/workarea
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
